version: "3"
services:
  web:
      image: nginx:latest
      ports:
          - "8443:443"
      volumes:
          - ./html:/usr/share/nginx/html
          - ./certs:/etc/nginx/certs/
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./access.log:/var/log/nginx/access.log
          - ./error.log:/var/log/nginx/error.log
      links:
          - php
  php:
      image: php:7-fpm
      volumes:
          - ./html:/usr/share/nginx/html
