version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8443:443"
    expose:
      - "443"
    stdin_open: true
    tty: true
    volumes:
        - ${PWD}/html:/usr/share/nginx/html
        - ${PWD}/certs:/etc/nginx/certs/
    links:
        - flask

  flask:
    build:
      context: .
      dockerfile: .docker/flask/Dockerfile
    expose:
      - "5000"
    volumes:
      - ${PWD}/flask_project_code:/opt/app/myproject
