version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8080:80"
    expose:
      - "80"
      - "443"
    stdin_open: true
    tty: true
    volumes:
        - ./html:/usr/share/nginx/html
    links:
        - flask
  flask:
    build:
      context: .
      dockerfile: .docker/flask/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./flask_project_code:/root/flask/myproject
