version: "3"

volumes:
  trustanchors:
  cabundle:
  cache_storage:
  se_storage:

services:
  trust:
    image: indigoiam/trustanchors
    environment:
      - FORCE_TRUST_ANCHORS_UPDATE=0
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - cabundle:/etc/pki
    networks:
      - cache

  cache.example:
    image: storm2/ngx-voms
    volumes: 
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - cache_storage:/data/nginx/cache
      - ./certs/cache:/certs
      - ./files/nginx_cache.conf:/home/build/local/openresty/nginx/conf/nginx.conf

    depends_on:
      - trust
    ports:
      - "3000:443"
    networks:
      - cache

  se.example:
    image: storm2/ngx-voms
    volumes: 
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./certs/se:/certs
      - ./files/nginx_se.conf:/home/build/local/openresty/nginx/conf/nginx.conf

    depends_on:
      - trust
    networks:
      - cache

  client:
    image: centos:latest
    environment:
      TZ: Europe/Rome

    volumes:
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - se_storage:/data/nginx/www
      - cache_storage:/data/nginx/cache
      - ./certs/client:/certs

    depends_on:
      - trust
      - se.example
      - cache.example

    networks:
      - cache
    entrypoint: sleep infinity

networks:
  cache:
    driver: bridge


